# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestForms():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_forms(self):
    self.driver.get("https://docs.google.com/forms/u/0/")
    self.driver.set_window_size(1371, 815)
    self.driver.find_element(By.CSS_SELECTOR, "#\\3A 38 > .docs-homescreen-grid-item-metadata-container").click()
    self.driver.find_element(By.CSS_SELECTOR, ".freebirdFormeditorViewTabResponsesViewTabContent").click()
    self.driver.find_element(By.CSS_SELECTOR, ".freebird-qp-icon-spreadsheet-green:nth-child(1)").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".isUndragged .appsMaterialWizButtonPaperbuttonLabel").click()
    self.vars["win2290"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win2290"])
    element = self.driver.find_element(By.ID, "waffle-rich-text-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<br><br>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".jfk-button-action").click()
    self.driver.switch_to.frame(4)
    self.driver.find_element(By.CSS_SELECTOR, ".mdc-deprecated-list-item__primary-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mdc-deprecated-chip-trailing-action__ripple").click()
    self.driver.find_element(By.ID, "_c10").send_keys("https://docs.google.com/forms/u/0/")
    self.driver.find_element(By.CSS_SELECTOR, ".mdc-ripple-upgraded--foreground-activation > .mdc-button__ripple").click()
    self.driver.switch_to.default_content()
    element = self.driver.find_element(By.CSS_SELECTOR, ".gb_Ca")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".docs-title-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".docs-title-input").send_keys("Formfile")
    self.driver.find_element(By.CSS_SELECTOR, ".docs-title-input").send_keys(Keys.ENTER)
  
