# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSheets():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sheets(self):
    self.driver.get("https://docs.google.com/spreadsheets/u/0/")
    self.driver.set_window_size(1369, 813)
    self.driver.find_element(By.CSS_SELECTOR, "#\\3A 1f img").click()
    self.driver.find_element(By.ID, "docs-title-widget").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".gb_Ca")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.ID, "waffle-rich-text-editor")
    self.driver.execute_script("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<br><br>'}", element)
    self.driver.find_element(By.CSS_SELECTOR, ".jfk-button-action").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".jfk-button-action")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".modal-dialog-bg:nth-child(144)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".docs-gm:nth-child(2)").click()
    self.driver.find_element(By.ID, ":u5.ie").send_keys("Basefile")
    self.driver.find_element(By.NAME, "ok").click()
    self.driver.find_element(By.CSS_SELECTOR, ".docs-promo-action-container").click()
    self.driver.switch_to.frame(3)
    self.driver.find_element(By.ID, "_c10").send_keys("classroomapp@western-arch-321815.iam.gserviceaccount.com")
    self.driver.find_element(By.ID, "_c10").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".boqDrivesharedialogCommonButtonbarShareButton > .mdc-button__ripple").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".boqDrivesharedialogCommonButtonbarShareButton > .mdc-button__ripple")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
